### ISSUE TITLE
Typescript not picking up undefined/null

### ISSUE THREAD

**Issue by iivic17** [nasheomirro/react-polymorphed#4]
```typescript
export type TypographyProps = {
	variant: keyof TypographyVariants<string>;
	className?: string | undefined;
	count?: number | null;
};

export const defaultComponent = 'span';

export type TypographyPolymorphicProps = PolymorphicComponent<
	typeof defaultComponent,
	PropsWithChildren<TypographyProps>
>;
```
and in such case
```typescript
const Typography: TypographyPolymorphicProps = ({
	as: As = defaultComponent,
	variant,
	className,
	children,
	count,
	...props
}) => {
```
The component will see className and count only as string/number, even though they are optional parameters and explicitly set to undefined/null

**Comment by iivic17** [comment]
![Screenshot 2023-04-04 at 12 13 40](https://user-images.githubusercontent.com/42393408/229760990-4ee7b8ea-cf9a-451a-bff5-4e7c2d45327d.png)

**Comment by nasheomirro** [comment]
Hey @iivic17 ,  this might be a problem with your typescript config having the `strictNullChecks` set to false. If your config doesn't have that, then I might need a ts playground that produces said issue cause I can't really reproduce it in other ways.
